alias nn="vi ~/nn"
alias ag='ag -i'
alias alp="aws configure list-profiles"
alias awsl='aws sso login'
alias cap="echo $AWS_PROFILE"
alias cd='z'
alias cls="clear"
alias cp="cp -v"
alias d2b="decimal2binary"
alias d='docker'
alias eap="ExportAWSProfile"
alias futc="from_utc"
alias g='git'
alias kns="kubens"
alias ktx="kubie ctx" 
alias la="ls -a"
alias lh="ls -d .?*"
alias ll="ls -la"
alias ls="lsd"
alias mkdir="mkdir -v"
alias mv="mv -v"
alias rep="cd $HOME/repo"
alias sdml='sdm login --email jon.duarte@mezmo.com'
alias simd='date +%Y%m%d%H%M'
alias tf="terraform"
alias tm="terramate"
alias tre="tre -p"
alias uap="UnsetAWSProfile"
alias utc="to_utc"
alias vi="nvim"
alias vi='nvim'
alias virc='vi ~/.zshrc'
