alias vi="nvim"
alias cls="clear"
alias simd='date +%Y%m%d%H%M'
alias cp="cp -v"
alias mv="mv -v"
alias ls="lsd"
alias la="ls -a"
alias rep="cd $HOME/repo"
alias tm="terramate"
alias tf="terraform"
alias d2b="decimal2binary"
alias eap="ExportAWSProfile"
alias uap="UnsetAWSProfile"
alias cap="echo $AWS_PROFILE"
alias utc="to_utc"
alias futc="from_utc"
alias alp="aws configure list-profiles"
alias ktx="kubectx"
alias kns="kubens"
alias g='git'
alias d='docker'
alias vi='nvim'
alias virc='vi ~/.zshrc'
alias sdml='sdm login --email jon.duarte@mezmo.com'
alias awsl='aws sso login'
alias cd='z'
